import { SOURCE_SEED } from "./telegram";
import { seedQuotes } from "./symbols";
import type {
  Account,
  AppSettings,
  CircuitState,
  ClosedTrade,
  DeskSnapshot,
  Position,
  RiskSettings,
  Signal,
  TelegramMessage,
} from "./types";

function risk(partial: Partial<RiskSettings> = {}): RiskSettings {
  return {
    mode: "percent",
    percent: 1,
    fixedLots: 0.1,
    fixedPips: 20,
    rr: 2,
    maxDailyLossPct: 4,
    maxOpenLots: 5,
    maxTradesPerDay: 40,
    maxConsecutiveLosses: 6,
    maxSlippagePips: 3,
    maxSpreadPips: 40,
    flattenOnTrip: false,
    fridayCutoffHour: 21,
    ...partial,
  };
}

export function seedAccounts(): Account[] {
  return [
    {
      id: "acc-master",
      name: "Volt Master",
      platform: "MT5",
      broker: "IC Markets",
      server: "ICMarketsSC-MT5-2",
      login: "50422187",
      role: "master",
      currency: "USD",
      leverage: 500,
      balance: 52480,
      equity: 52480,
      margin: 0,
      connected: true,
      pingMs: 11,
      frozen: false,
      receivesSignals: true,
      risk: risk({ percent: 0.8, maxOpenLots: 8 }),
    },
    {
      id: "acc-copy-a",
      name: "Exness Copy",
      platform: "MT4",
      broker: "Exness",
      server: "Exness-Real3",
      login: "88120411",
      role: "follower",
      currency: "USD",
      leverage: 400,
      balance: 12410,
      equity: 12410,
      margin: 0,
      connected: true,
      pingMs: 18,
      frozen: false,
      receivesSignals: false,
      risk: risk({ mode: "fixed_lots", fixedLots: 0.05, maxOpenLots: 2 }),
      copy: {
        masterId: "acc-master",
        multiplier: 0.4,
        reverse: false,
        equityScale: false,
        maxLot: 1.2,
        delayMs: 0,
        symbolSuffix: "",
      },
    },
    {
      id: "acc-prop",
      name: "FTMO 100k",
      platform: "MT5",
      broker: "FTMO",
      server: "FTMO-Server3",
      login: "11092844",
      role: "follower",
      currency: "USD",
      leverage: 100,
      balance: 100_000,
      equity: 100_000,
      margin: 0,
      connected: true,
      pingMs: 9,
      frozen: false,
      receivesSignals: false,
      risk: risk({
        mode: "percent",
        percent: 0.4,
        maxDailyLossPct: 2,
        maxOpenLots: 4,
        flattenOnTrip: true,
      }),
      copy: {
        masterId: "acc-master",
        multiplier: 0.25,
        reverse: false,
        equityScale: true,
        maxLot: 2,
        delayMs: 40,
        symbolSuffix: ".pro",
      },
    },
    {
      id: "acc-personal",
      name: "Pepperstone Scalp",
      platform: "MT5",
      broker: "Pepperstone",
      server: "Pepperstone-MT5-Live2",
      login: "3340912",
      role: "independent",
      currency: "USD",
      leverage: 200,
      balance: 8250,
      equity: 8250,
      margin: 0,
      connected: true,
      pingMs: 14,
      frozen: false,
      receivesSignals: true,
      risk: risk({ mode: "rr", percent: 0.5, rr: 2.5, maxOpenLots: 1.5 }),
    },
  ];
}

const SETTINGS: AppSettings = {
  autoInterpret: true,
  grokFallback: false,
  grokCallsUsed: 0,
  grokCallCap: 8,
  beAfterTp1: true,
  tpSplit: [50, 30, 20],
  defaultTrailingPips: null,
  paper: true,
};

function at(now: number, minutesAgo: number): number {
  return now - minutesAgo * 60_000;
}

export function seedHistory(now: number): ClosedTrade[] {
  const rows: Array<Omit<ClosedTrade, "id"> & { id?: string }> = [
    { ticket: 18419901, accountId: "acc-master", signalNumber: 138, sourceId: "gold-sniper", symbol: "XAUUSD", side: "buy", lots: 0.42, openPrice: 3671.2, closePrice: 3682.4, sl: 3664.1, tp: 3688, profit: 470.4, openTime: at(now, 420), closeTime: at(now, 310), comment: "TP2" },
    { ticket: 18419902, accountId: "acc-copy-a", signalNumber: 138, sourceId: "gold-sniper", symbol: "XAUUSD", side: "buy", lots: 0.17, openPrice: 3671.22, closePrice: 3682.41, sl: 3664.1, tp: 3688, profit: 190.23, openTime: at(now, 420), closeTime: at(now, 310), comment: "copy TP2" },
    { ticket: 18419908, accountId: "acc-master", signalNumber: 139, sourceId: "fx-masters", symbol: "EURUSD", side: "sell", lots: 1.2, openPrice: 1.08612, closePrice: 1.0844, sl: 1.0878, tp: 1.0832, profit: 206.4, openTime: at(now, 380), closeTime: at(now, 240), comment: "TP1" },
    { ticket: 18419911, accountId: "acc-master", signalNumber: 140, sourceId: "indices-desk", symbol: "NAS100", side: "buy", lots: 0.8, openPrice: 20012.4, closePrice: 19974.1, sl: 19974, tp: 20110, profit: -30.64, openTime: at(now, 300), closeTime: at(now, 250), comment: "SL" },
    { ticket: 18419914, accountId: "acc-personal", signalNumber: 141, sourceId: "london-scalps", symbol: "GBPUSD", side: "buy", lots: 0.2, openPrice: 1.3102, closePrice: 1.3129, sl: 1.3084, tp: 1.3148, profit: 54, openTime: at(now, 210), closeTime: at(now, 140), comment: "TP1" },
    { ticket: 18419918, accountId: "acc-master", signalNumber: 142, sourceId: "vip-circle", symbol: "GBPJPY", side: "sell", lots: 0.6, openPrice: 194.88, closePrice: 194.41, sl: 195.22, tp: 194.1, profit: 282, openTime: at(now, 180), closeTime: at(now, 90), comment: "TP1" },
    { ticket: 18419921, accountId: "acc-prop", signalNumber: 142, sourceId: "vip-circle", symbol: "GBPJPY", side: "sell", lots: 0.4, openPrice: 194.882, closePrice: 194.412, sl: 195.22, tp: 194.1, profit: 188, openTime: at(now, 180), closeTime: at(now, 90), comment: "copy" },
    { ticket: 18419924, accountId: "acc-master", signalNumber: 143, sourceId: "gold-sniper", symbol: "XAUUSD", side: "sell", lots: 0.3, openPrice: 3691.8, closePrice: 3698.2, sl: 3698.1, tp: 3674, profit: -192, openTime: at(now, 160), closeTime: at(now, 120), comment: "SL" },
    { ticket: 18419928, accountId: "acc-master", signalNumber: 144, sourceId: "fx-masters", symbol: "USDJPY", side: "buy", lots: 1.0, openPrice: 147.92, closePrice: 148.18, sl: 147.71, tp: 148.4, profit: 175.4, openTime: at(now, 110), closeTime: at(now, 40), comment: "TP1" },
    { ticket: 18419931, accountId: "acc-personal", signalNumber: null, sourceId: null, symbol: "USOIL", side: "buy", lots: 0.15, openPrice: 71.92, closePrice: 72.44, sl: 71.4, tp: 73.1, profit: 78, openTime: at(now, 96), closeTime: at(now, 28), comment: "manual" },
    { ticket: 18419933, accountId: "acc-copy-a", signalNumber: 144, sourceId: "fx-masters", symbol: "USDJPY", side: "buy", lots: 0.4, openPrice: 147.922, closePrice: 148.181, sl: 147.71, tp: 148.4, profit: 70.1, openTime: at(now, 110), closeTime: at(now, 40), comment: "copy" },
    { ticket: 18419936, accountId: "acc-master", signalNumber: 145, sourceId: "crypto-pulse", symbol: "BTCUSD", side: "buy", lots: 0.08, openPrice: 96810, closePrice: 97140, sl: 96120, tp: 97800, profit: 26.4, openTime: at(now, 80), closeTime: at(now, 22), comment: "partial" },
  ];
  return rows.map((r, i) => ({
    ...r,
    id: `hist_${i + 1}`,
  }));
}

export function seedPositions(now: number): Position[] {
  return [
    {
      id: "pos_live_1",
      ticket: 18420002,
      accountId: "acc-master",
      signalId: "sig_146",
      signalNumber: 146,
      sourceId: "gold-sniper",
      symbol: "XAUUSD",
      side: "buy",
      lots: 0.36,
      openPrice: 3681.4,
      sl: 3674.2,
      tp: 3704.8,
      tps: [
        { price: 3690.2, closePct: 50, hit: false },
        { price: 3697.4, closePct: 30, hit: false },
        { price: 3704.8, closePct: 100, hit: false },
      ],
      beAfterTp1: true,
      trailingPips: null,
      openTime: at(now, 38),
      magic: 146001,
      comment: "VOLT 0146 Volt Master",
      commission: 1.26,
    },
    {
      id: "pos_live_2",
      ticket: 18420003,
      accountId: "acc-copy-a",
      signalId: "sig_146",
      signalNumber: 146,
      sourceId: "gold-sniper",
      copiedFrom: "acc-master",
      symbol: "XAUUSD",
      side: "buy",
      lots: 0.14,
      openPrice: 3681.44,
      sl: 3674.2,
      tp: 3704.8,
      tps: [{ price: 3690.2, closePct: 50, hit: false }, { price: 3704.8, closePct: 100, hit: false }],
      beAfterTp1: true,
      trailingPips: null,
      openTime: at(now, 38),
      magic: 146002,
      comment: "VOLT 0146 Exness Copy",
      commission: 0.49,
    },
    {
      id: "pos_live_3",
      ticket: 18420005,
      accountId: "acc-master",
      signalId: "sig_147",
      signalNumber: 147,
      sourceId: "fx-masters",
      symbol: "EURUSD",
      side: "sell",
      lots: 1.1,
      openPrice: 1.08502,
      sl: 1.0868,
      tp: 1.0814,
      tps: [
        { price: 1.0836, closePct: 50, hit: false },
        { price: 1.0814, closePct: 100, hit: false },
      ],
      beAfterTp1: true,
      trailingPips: null,
      openTime: at(now, 22),
      magic: 147001,
      comment: "VOLT 0147 Volt Master",
      commission: 3.85,
    },
    {
      id: "pos_live_4",
      ticket: 18420007,
      accountId: "acc-personal",
      signalId: "sig_148",
      signalNumber: 148,
      sourceId: "indices-desk",
      symbol: "NAS100",
      side: "buy",
      lots: 0.4,
      openPrice: 20112.2,
      sl: 20040,
      tp: 20280,
      tps: [{ price: 20190, closePct: 50, hit: false }, { price: 20280, closePct: 100, hit: false }],
      beAfterTp1: true,
      trailingPips: 18,
      openTime: at(now, 14),
      magic: 148003,
      comment: "VOLT 0148 Pepperstone Scalp",
      commission: 1.4,
    },
    {
      id: "pos_live_5",
      ticket: 18420008,
      accountId: "acc-prop",
      signalId: "sig_146",
      signalNumber: 146,
      sourceId: "gold-sniper",
      copiedFrom: "acc-master",
      symbol: "XAUUSD",
      side: "buy",
      lots: 0.22,
      openPrice: 3681.5,
      sl: 3674.2,
      tp: 3704.8,
      tps: [{ price: 3690.2, closePct: 50, hit: false }, { price: 3704.8, closePct: 100, hit: false }],
      beAfterTp1: true,
      trailingPips: null,
      openTime: at(now, 38),
      magic: 146002,
      comment: "VOLT 0146 FTMO 100k",
      commission: 0.77,
    },
  ];
}

export function seedSignals(now: number): Signal[] {
  const emptyLat = {
    receiveMs: 0,
    parseMs: 0.4,
    riskMs: 0.1,
    routeMs: 0.2,
    fillMs: 8,
    totalMs: 9,
  };
  return [
    {
      id: "sig_146",
      number: 146,
      sourceId: "gold-sniper",
      telegramMsgId: "tg_146",
      rawText: "XAUUSD BUY NOW\nEntry: 3680.40 - 3682.20\nSL: 3674.20\nTP1: 3690.20\nTP2: 3697.40\nTP3: 3704.80",
      parsed: {
        symbol: "XAUUSD",
        side: "buy",
        orderType: "market",
        entry: 3680.4,
        entryMax: 3682.2,
        sl: 3674.2,
        tps: [3690.2, 3697.4, 3704.8],
        action: "open",
      },
      confidence: 0.96,
      interpreter: "local",
      status: "live",
      receivedAt: at(now, 38),
      latency: { ...emptyLat, totalMs: 11, fillMs: 10 },
    },
    {
      id: "sig_147",
      number: 147,
      sourceId: "fx-masters",
      telegramMsgId: "tg_147",
      rawText: "EURUSD SELL\nSL 1.08680\nTP 1.08360\nTP2 1.08140",
      parsed: {
        symbol: "EURUSD",
        side: "sell",
        orderType: "market",
        sl: 1.0868,
        tps: [1.0836, 1.0814],
        action: "open",
      },
      confidence: 0.93,
      interpreter: "local",
      status: "live",
      receivedAt: at(now, 22),
      latency: { ...emptyLat, totalMs: 8 },
    },
    {
      id: "sig_148",
      number: 148,
      sourceId: "indices-desk",
      telegramMsgId: "tg_148",
      rawText: "NAS100 BUY NOW\nEntry 20112\nSL 20040\nTP 20190 / 20280",
      parsed: {
        symbol: "NAS100",
        side: "buy",
        orderType: "market",
        entry: 20112,
        sl: 20040,
        tps: [20190, 20280],
        action: "open",
      },
      confidence: 0.91,
      interpreter: "local",
      status: "live",
      receivedAt: at(now, 14),
      latency: { ...emptyLat, totalMs: 13 },
    },
    {
      id: "sig_149",
      number: 149,
      sourceId: "crypto-pulse",
      telegramMsgId: "tg_149",
      rawText: "btc looking heavy into the round number, maybe a scalp short if we fail — not financial advice",
      confidence: 0.28,
      interpreter: "local",
      status: "received",
      receivedAt: at(now, 6),
      latency: { receiveMs: 0, parseMs: 0.3, riskMs: 0, routeMs: 0, fillMs: 0, totalMs: 0.3 },
      note: "low confidence · awaiting Grok",
    },
  ];
}

export function seedMessages(now: number): TelegramMessage[] {
  const sigs = seedSignals(now);
  return [
    {
      id: "tg_146",
      sourceId: "gold-sniper",
      text: sigs[0]!.rawText,
      at: sigs[0]!.receivedAt,
      from: "Aisha",
      interpreted: true,
      signalId: "sig_146",
    },
    {
      id: "tg_147",
      sourceId: "fx-masters",
      text: sigs[1]!.rawText,
      at: sigs[1]!.receivedAt,
      from: "Desk",
      interpreted: true,
      signalId: "sig_147",
    },
    {
      id: "tg_148",
      sourceId: "indices-desk",
      text: sigs[2]!.rawText,
      at: sigs[2]!.receivedAt,
      from: "Lina",
      interpreted: true,
      signalId: "sig_148",
    },
    {
      id: "tg_149",
      sourceId: "crypto-pulse",
      text: sigs[3]!.rawText,
      at: sigs[3]!.receivedAt,
      from: "Kenji",
      interpreted: false,
      signalId: "sig_149",
    },
    {
      id: "tg_note_1",
      sourceId: "london-scalps",
      text: "London open, spreads are fine. Waiting on cable.",
      at: at(now, 11),
      from: "Priya",
      interpreted: false,
    },
    {
      id: "tg_note_2",
      sourceId: "oil-wire",
      text: "Inventory later. No trade until the print.",
      at: at(now, 4),
      from: "Wire",
      interpreted: false,
    },
  ].sort((a, b) => b.at - a.at);
}

export function seedCircuits(now: number, startEquity: number): CircuitState {
  void now;
  return {
    globalHalt: false,
    dailyLossTripped: false,
    consecutiveLosses: 1,
    tradesToday: 9,
    dayStartEquity: startEquity,
    realizedToday: 612.4,
    spreadPause: false,
    reason: null,
  };
}

export function createSeed(now = Date.now()): DeskSnapshot {
  const accounts = seedAccounts();
  const quotes = seedQuotes(now);
  const positions = seedPositions(now);
  const history = seedHistory(now);
  const start = accounts.reduce((s, a) => s + a.balance, 0);
  return {
    accounts,
    sources: SOURCE_SEED.map((s) => ({ ...s })),
    messages: seedMessages(now),
    signals: seedSignals(now),
    positions,
    orders: [
      {
        id: "ord_1",
        ticket: 18420012,
        accountId: "acc-master",
        signalId: null,
        signalNumber: 150,
        sourceId: "fx-masters",
        symbol: "GBPUSD",
        side: "buy",
        type: "buy_limit",
        lots: 0.7,
        price: 1.3098,
        sl: 1.3072,
        tp: 1.3164,
        tps: [
          { price: 1.3128, closePct: 50, hit: false },
          { price: 1.3164, closePct: 100, hit: false },
        ],
        createdAt: at(now, 9),
        magic: 150001,
        comment: "VOLT 0150 Volt Master",
      },
    ],
    history,
    quotes,
    circuits: seedCircuits(now, start),
    telegram: {
      connected: true,
      connecting: false,
      user: "volt.desk",
      phone: "+44 •• •• 19",
    },
    settings: { ...SETTINGS },
    log: [
      {
        id: "ev_seed_1",
        at: at(now, 38),
        kind: "fill",
        text: "Filled BUY 0.36 XAUUSD @ 3681.40 · Volt Master",
        latencyMs: 11,
        signalNumber: 146,
      },
      {
        id: "ev_seed_2",
        at: at(now, 38),
        kind: "copy",
        text: "Copied #0146 → Exness Copy 0.14 lots",
        signalNumber: 146,
      },
      {
        id: "ev_seed_3",
        at: at(now, 22),
        kind: "fill",
        text: "Filled SELL 1.10 EURUSD @ 1.08502 · Volt Master",
        latencyMs: 8,
        signalNumber: 147,
      },
      {
        id: "ev_seed_4",
        at: at(now, 6),
        kind: "parse",
        text: "Low confidence on Crypto Pulse — held",
        signalNumber: 149,
      },
    ],
    equity: Array.from({ length: 48 }, (_, i) => ({
      t: now - (47 - i) * 5 * 60_000,
      equity: start - 420 + Math.sin(i / 4) * 280 + i * 18,
    })),
    nextSignalNumber: 150,
    nextTicket: 18420020,
    now,
  };
}
