/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeskRouteImport } from './routes/_desk'
import { Route as DeskIndexRouteImport } from './routes/_desk/index'
import { Route as DeskAccountsRouteImport } from './routes/_desk/accounts'
import { Route as DeskBookRouteImport } from './routes/_desk/book'
import { Route as DeskBridgeRouteImport } from './routes/_desk/bridge'
import { Route as DeskHistoryRouteImport } from './routes/_desk/history'
import { Route as DeskProvidersRouteImport } from './routes/_desk/providers'
import { Route as DeskRiskRouteImport } from './routes/_desk/risk'
import { Route as DeskSettingsRouteImport } from './routes/_desk/settings'
import { Route as DeskSignalsRouteImport } from './routes/_desk/signals'
import { Route as DeskTelegramRouteImport } from './routes/_desk/telegram'

const DeskRoute = DeskRouteImport.update({
  id: '/_desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskAccountsRoute = DeskAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DeskRoute,
} as any)
const DeskBookRoute = DeskBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => DeskRoute,
} as any)
const DeskBridgeRoute = DeskBridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => DeskRoute,
} as any)
const DeskHistoryRoute = DeskHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DeskRoute,
} as any)
const DeskProvidersRoute = DeskProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => DeskRoute,
} as any)
const DeskRiskRoute = DeskRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSettingsRoute = DeskSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSignalsRoute = DeskSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTelegramRoute = DeskTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => DeskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DeskIndexRoute
  '/accounts': typeof DeskAccountsRoute
  '/book': typeof DeskBookRoute
  '/bridge': typeof DeskBridgeRoute
  '/history': typeof DeskHistoryRoute
  '/providers': typeof DeskProvidersRoute
  '/risk': typeof DeskRiskRoute
  '/settings': typeof DeskSettingsRoute
  '/signals': typeof DeskSignalsRoute
  '/telegram': typeof DeskTelegramRoute
}
export interface FileRoutesByTo {
  '/accounts': typeof DeskAccountsRoute
  '/book': typeof DeskBookRoute
  '/bridge': typeof DeskBridgeRoute
  '/history': typeof DeskHistoryRoute
  '/providers': typeof DeskProvidersRoute
  '/risk': typeof DeskRiskRoute
  '/settings': typeof DeskSettingsRoute
  '/signals': typeof DeskSignalsRoute
  '/telegram': typeof DeskTelegramRoute
  '/': typeof DeskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_desk': typeof DeskRouteWithChildren
  '/_desk/accounts': typeof DeskAccountsRoute
  '/_desk/book': typeof DeskBookRoute
  '/_desk/bridge': typeof DeskBridgeRoute
  '/_desk/history': typeof DeskHistoryRoute
  '/_desk/providers': typeof DeskProvidersRoute
  '/_desk/risk': typeof DeskRiskRoute
  '/_desk/settings': typeof DeskSettingsRoute
  '/_desk/signals': typeof DeskSignalsRoute
  '/_desk/telegram': typeof DeskTelegramRoute
  '/_desk/': typeof DeskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/book'
    | '/bridge'
    | '/history'
    | '/providers'
    | '/risk'
    | '/settings'
    | '/signals'
    | '/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accounts'
    | '/book'
    | '/bridge'
    | '/history'
    | '/providers'
    | '/risk'
    | '/settings'
    | '/signals'
    | '/telegram'
    | '/'
  id:
    | '__root__'
    | '/_desk'
    | '/_desk/accounts'
    | '/_desk/book'
    | '/_desk/bridge'
    | '/_desk/history'
    | '/_desk/providers'
    | '/_desk/risk'
    | '/_desk/settings'
    | '/_desk/signals'
    | '/_desk/telegram'
    | '/_desk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DeskRoute: typeof DeskRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_desk': {
      id: '/_desk'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_desk/': {
      id: '/_desk/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/accounts': {
      id: '/_desk/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof DeskAccountsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/book': {
      id: '/_desk/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof DeskBookRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/bridge': {
      id: '/_desk/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof DeskBridgeRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/history': {
      id: '/_desk/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof DeskHistoryRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/providers': {
      id: '/_desk/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof DeskProvidersRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/risk': {
      id: '/_desk/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof DeskRiskRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/settings': {
      id: '/_desk/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DeskSettingsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/signals': {
      id: '/_desk/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof DeskSignalsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/telegram': {
      id: '/_desk/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof DeskTelegramRouteImport
      parentRoute: typeof DeskRoute
    }
  }
}

interface DeskRouteChildren {
  DeskAccountsRoute: typeof DeskAccountsRoute
  DeskBookRoute: typeof DeskBookRoute
  DeskBridgeRoute: typeof DeskBridgeRoute
  DeskHistoryRoute: typeof DeskHistoryRoute
  DeskProvidersRoute: typeof DeskProvidersRoute
  DeskRiskRoute: typeof DeskRiskRoute
  DeskSettingsRoute: typeof DeskSettingsRoute
  DeskSignalsRoute: typeof DeskSignalsRoute
  DeskTelegramRoute: typeof DeskTelegramRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskAccountsRoute: DeskAccountsRoute,
  DeskBookRoute: DeskBookRoute,
  DeskBridgeRoute: DeskBridgeRoute,
  DeskHistoryRoute: DeskHistoryRoute,
  DeskProvidersRoute: DeskProvidersRoute,
  DeskRiskRoute: DeskRiskRoute,
  DeskSettingsRoute: DeskSettingsRoute,
  DeskSignalsRoute: DeskSignalsRoute,
  DeskTelegramRoute: DeskTelegramRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DeskRoute: DeskRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
